# Docker Compose Override for Development
# This file is automatically loaded by docker-compose and provides development-specific overrides

version: '3.8'

services:
  mcp-server:
    # Override for development with hot-reload
    build:
      target: builder  # Use builder stage for development
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      - ./logs:/app/logs
    command: ["npm", "run", "dev"]  # Use development command with hot-reload
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    # Enable debugging port
    ports:
      - "3000:3000"
      - "3001:3001"
      - "9229:9229"  # Node.js debugging port